### ISSUE TITLE
오류 수정 요청

### ISSUE THREAD

**Issue by PreviousW** [noobnuby/kotlin-plugin-template#1]
https://github.com/NOOBNUBY/kotlin-plugin-template/blob/master/src/main/kotlin/com/noobnuby/plugin/events/JoinQuit.kt#L13

p를 바로 대입 => CraftPlayer,, 어쩌고 저쩌고 뜸

p`.name` 붙이기

**Comment by noobnuby** [comment]
넵 알겠습니다
